export { buildResearcherPrompt } from "./researcher"
export { buildAdvocatePrompt } from "./advocate"
export { buildCriticPrompt } from "./critic"
export { buildSynthesizerPrompt } from "./synthesizer"
export { buildDevilsAdvocatePrompt } from "./devils-advocate"
